### ISSUE TITLE
Cannot find module 'jose/jwk/from_key_like

### ISSUE THREAD

**Issue by mrosendin** [payid-org/payid-cli#7]
Using Ubuntu 18.04 LTS AMI, PayString CLI 2.0.0

```
root@ip-172-31-20-217:~/paystring# paystring help
module.js:549
    throw err;
    ^

Error: Cannot find module 'jose/jwk/from_key_like'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@paystring/paystring-cli/node_modules/@paystring/utils/dist/verifiable/keys.js:4:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by sappenin** [comment]
@nhartner Any thoughts here?

**Comment by nhartner** [comment]
@mrosendin what version of Node do you have installed? I was able to reproduce your error on a Ubuntu image with Node 10 installed. It looks like the Jose library dependency needs a newer version of node. I was able to fix this on my Ubuntu by upgrading to Node 14. This is the guide I followed to update Node: https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/

**Comment by mrosendin** [comment]
That resolved it @nhartner ! Thank you so much.
